import React, { useState, useRef } from 'react';
import { Film, UploadCloud, ShieldAlert, ShieldCheck, Download, RefreshCw, AlertTriangle, CheckCircle, Cpu, Eye, Lock } from 'lucide-react';

export default function DeepfakeFaceScanner({ onScanComplete }) {
  const [videoFile, setVideoFile] = useState(null);
  const [videoPreview, setVideoPreview] = useState(null);
  const [isScanning, setIsScanning] = useState(false);
  const [report, setReport] = useState(null);
  const fileInputRef = useRef(null);

  const handleFileDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer ? e.dataTransfer.files[0] : e.target.files[0];
    if (!file) return;

    if (!file.type.includes('video') && !/\.(mp4|mov|avi|webm|mkv)$/i.test(file.name)) {
      alert('Please upload a valid video file (.mp4, .mov, .avi, .webm).');
      return;
    }

    setVideoFile(file);
    setVideoPreview(URL.createObjectURL(file));
    setReport(null);
  };

  const runVideoFaceScan = async () => {
    if (!videoFile) return;

    setIsScanning(true);
    try {
      const formData = new FormData();
      formData.append('video', videoFile);

      const response = await fetch('/api/deepfake/face-scan', {
        method: 'POST',
        body: JSON.stringify({ fileName: videoFile.name, fileType: videoFile.type, fileSize: videoFile.size }),
        headers: { 'Content-Type': 'application/json' }
      });
      const data = await response.json();

      setTimeout(() => {
        setReport(data);
        setIsScanning(false);
        if (onScanComplete) onScanComplete(data);
      }, 2000);

    } catch (err) {
      alert('Video Face Scan Error: ' + err.message);
      setIsScanning(false);
    }
  };

  const handleDownloadReport = () => {
    if (!report) return;
    const reportStr = `GUARDX DEEPFAKE FACE SCANNER - SECURITY ANALYSIS REPORT
=====================================================
Timestamp: ${new Date().toISOString()}
File Analyzed: ${report.fileName || 'Uploaded_Video.mp4'}

ANALYSIS SUMMARY:
-----------------
Classification: [${report.classification}]
AI Manipulation Probability: ${report.aiManipulationProbability}%
Face Swap Detection: ${report.faceSwapDetection}
Lip Sync Accuracy: ${report.lipSyncAccuracy}%
Facial Movement Analysis: ${report.facialMovementAnalysis}
Expression / Blinking Check: ${report.expressionAnalysis}
Overall Trust Score: ${report.trustScore}/100
Risk Level: ${report.riskLevel}

EXPLANATION:
------------
${report.explanation}

LEGAL DISCLAIMER:
-----------------
Analysis results are AI-based probabilistic predictions generated by GuardX Gateway.
Zero Permanent Storage Policy: Video payload automatically purged from memory.
=====================================================`;

    const blob = new Blob([reportStr], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GuardX_Deepfake_Report_${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const resetScan = () => {
    setVideoFile(null);
    setVideoPreview(null);
    setReport(null);
  };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1.1fr 1fr', gap: '24px', alignItems: 'start' }}>
      
      {/* Left Column: Upload & Video Player */}
      <div style={{ background: '#FAFAFA', border: '1px solid #E4E4E7', borderRadius: '12px', padding: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
          <h3 style={{ fontSize: '1.15rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '10px', color: '#18181B' }}>
            <Film style={{ color: '#2563EB', width: '22px', height: '22px' }} />
            Deepfake Face Scanner 🎭
          </h3>
          <span style={{ fontSize: '0.72rem', background: 'rgba(37, 99, 235, 0.1)', color: '#2563EB', padding: '3px 8px', borderRadius: '6px', fontWeight: 700, border: '1px solid rgba(37, 99, 235, 0.2)' }}>
            VIDEO FACE AI
          </span>
        </div>

        {/* Drag & Drop Upload Zone */}
        {!videoPreview ? (
          <div
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleFileDrop}
            onClick={() => fileInputRef.current?.click()}
            style={{
              border: '2px dashed #D4D4D8',
              borderRadius: '12px',
              padding: '36px 20px',
              textAlign: 'center',
              cursor: 'pointer',
              background: '#FFFFFF',
              transition: '0.2s',
              marginBottom: '16px'
            }}
          >
            <div style={{ width: '54px', height: '54px', borderRadius: '50%', background: 'rgba(37, 99, 235, 0.1)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: '#2563EB', marginBottom: '12px' }}>
              <UploadCloud size={28} />
            </div>
            <div style={{ fontWeight: 700, fontSize: '1rem', color: '#18181B' }}>Drag & Drop Video File Here</div>
            <div style={{ fontSize: '0.8rem', color: '#52525B', marginTop: '4px' }}>Supports .mp4, .mov, .avi, .webm (Up to 50MB)</div>
            <input ref={fileInputRef} type="file" accept="video/*" style={{ display: 'none' }} onChange={handleFileDrop} />
          </div>
        ) : (
          <div style={{ marginBottom: '16px' }}>
            {/* Video Player Preview with Animated Scanner Overlay */}
            <div style={{ position: 'relative', width: '100%', background: '#000', borderRadius: '12px', overflow: 'hidden', border: '1px solid #E4E4E7', minHeight: '240px' }}>
              <video src={videoPreview} controls style={{ width: '100%', maxHeight: '300px', objectFit: 'contain', display: 'block' }} />
              
              {/* Laser Line Scanning Effect Animation */}
              {isScanning && (
                <div style={{
                  position: 'absolute',
                  inset: 0,
                  background: 'rgba(37, 99, 235, 0.15)',
                  pointerEvents: 'none',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}>
                  <div style={{
                    position: 'absolute',
                    top: '0%',
                    left: '0',
                    right: '0',
                    height: '4px',
                    background: '#2563EB',
                    boxShadow: '0 0 15px #2563EB',
                    animation: 'scanLaser 1.5s infinite linear'
                  }} />
                  <div style={{ background: '#18181B', color: '#FFF', padding: '8px 16px', borderRadius: '8px', fontWeight: 700, fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.5)' }}>
                    <Cpu size={16} className="animate-spin text-blue-500" />
                    Scanning Facial Geometry & Temporal Motion...
                  </div>
                </div>
              )}
            </div>

            <div style={{ display: 'flex', gap: '10px', marginTop: '12px' }}>
              <button
                onClick={runVideoFaceScan}
                disabled={isScanning}
                style={{
                  flex: 1,
                  background: '#2563EB',
                  color: '#FFF',
                  fontWeight: 700,
                  padding: '12px 18px',
                  border: 'none',
                  borderRadius: '10px',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '8px'
                }}
              >
                {isScanning ? <RefreshCw size={18} className="animate-spin" /> : <Eye size={18} />}
                {isScanning ? 'Analyzing Video...' : 'Analyze Face Video'}
              </button>
              <button
                onClick={resetScan}
                disabled={isScanning}
                style={{
                  background: '#FFFFFF',
                  color: '#52525B',
                  border: '1px solid #E4E4E7',
                  padding: '12px 16px',
                  borderRadius: '10px',
                  cursor: 'pointer',
                  fontWeight: 600
                }}
              >
                Change
              </button>
            </div>
          </div>
        )}

        {/* Privacy & Auto-Purge Guarantee */}
        <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', padding: '12px 14px', borderRadius: '10px', fontSize: '0.78rem', color: '#52525B', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Lock size={16} style={{ color: '#16A34A', flexShrink: 0 }} />
          <span><strong>Zero Storage Policy:</strong> Video bytes are processed strictly in volatile RAM and automatically purged immediately post-analysis.</span>
        </div>
      </div>

      {/* Right Column: Security Analysis Report */}
      <div style={{ background: '#FAFAFA', border: '1px solid #E4E4E7', borderRadius: '12px', padding: '24px' }}>
        <h3 style={{ fontSize: '1.15rem', fontWeight: 800, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px', color: '#18181B' }}>
          <ShieldAlert style={{ color: '#2563EB', width: '22px', height: '22px' }} />
          Deepfake Analysis Report
        </h3>

        {!report ? (
          <div style={{ color: '#52525B', fontSize: '0.9rem', textAlign: 'center', padding: '60px 0' }}>
            Upload a video file and click <strong>Analyze Face Video</strong> to run deepfake face detection.
          </div>
        ) : (
          <div style={{ spaceY: '16px' }}>
            
            {/* Header Score Cards */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '16px' }}>
              
              {/* Trust Score */}
              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '10px', padding: '14px', textAlign: 'center' }}>
                <div style={{ fontSize: '0.72rem', fontWeight: 700, textTransform: 'uppercase', color: '#52525B' }}>Overall Trust Score</div>
                <div style={{ fontSize: '1.6rem', fontWeight: 800, color: report.trustScore > 70 ? '#16A34A' : '#DC2626', marginTop: '2px' }}>
                  {report.trustScore}/100
                </div>
              </div>

              {/* AI Manipulation Probability */}
              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '10px', padding: '14px', textAlign: 'center' }}>
                <div style={{ fontSize: '0.72rem', fontWeight: 700, textTransform: 'uppercase', color: '#52525B' }}>AI Manipulation</div>
                <div style={{ fontSize: '1.6rem', fontWeight: 800, color: report.aiManipulationProbability > 50 ? '#DC2626' : '#16A34A', marginTop: '2px' }}>
                  {report.aiManipulationProbability}%
                </div>
              </div>

            </div>

            {/* Main Verdict Badge */}
            <div style={{
              background: report.isAiGenerated ? '#FEE2E2' : '#DCFCE7',
              border: `1px solid ${report.isAiGenerated ? '#FCA5A5' : '#86EFAC'}`,
              color: report.isAiGenerated ? '#DC2626' : '#16A34A',
              borderRadius: '10px',
              padding: '12px 16px',
              fontWeight: 800,
              fontSize: '1rem',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: '16px'
            }}>
              <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                {report.isAiGenerated ? <AlertTriangle size={20} /> : <CheckCircle size={20} />}
                {report.classification}
              </span>
              <span style={{ fontSize: '0.75rem', textTransform: 'uppercase', background: report.isAiGenerated ? '#DC2626' : '#16A34A', color: '#FFF', padding: '3px 8px', borderRadius: '6px' }}>
                {report.riskLevel}
              </span>
            </div>

            {/* Feature Breakdown Metrics */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginBottom: '16px' }}>
              
              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '8px', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#18181B' }}>Face Swap Detection</span>
                <span style={{ fontSize: '0.82rem', fontWeight: 800, color: report.faceSwapDetection === 'Detected' ? '#DC2626' : '#16A34A' }}>
                  {report.faceSwapDetection}
                </span>
              </div>

              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '8px', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#18181B' }}>Lip Sync Accuracy</span>
                <span style={{ fontSize: '0.82rem', fontWeight: 800, color: report.lipSyncAccuracy < 60 ? '#DC2626' : '#16A34A' }}>
                  {report.lipSyncAccuracy}%
                </span>
              </div>

              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '8px', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#18181B' }}>Facial Movement Analysis</span>
                <span style={{ fontSize: '0.82rem', fontWeight: 800, color: report.facialMovementAnalysis === 'Suspicious' ? '#DC2626' : '#16A34A' }}>
                  {report.facialMovementAnalysis}
                </span>
              </div>

              <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', borderRadius: '8px', padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#18181B' }}>Inconsistent Blinking / Expression</span>
                <span style={{ fontSize: '0.82rem', fontWeight: 800, color: report.expressionAnalysis.includes('Artifacts') ? '#DC2626' : '#16A34A' }}>
                  {report.expressionAnalysis}
                </span>
              </div>

            </div>

            {/* Plain English Explanation */}
            <div style={{ background: '#FFFFFF', border: '1px solid #E4E4E7', padding: '12px 14px', borderRadius: '10px', fontSize: '0.85rem', color: '#18181B', lineHeight: 1.5, marginBottom: '16px' }}>
              {report.explanation}
            </div>

            {/* Actions & Legal Disclaimer */}
            <button
              onClick={handleDownloadReport}
              style={{
                width: '100%',
                background: '#18181B',
                color: '#FFF',
                fontWeight: 700,
                padding: '12px',
                border: 'none',
                borderRadius: '10px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                fontSize: '0.9rem',
                marginBottom: '10px'
              }}
            >
              <Download size={16} /> Download Security Report
            </button>

            <div style={{ fontSize: '0.72rem', color: '#71717A', textAlign: 'center' }}>
              <em>Disclaimer: Analysis results are AI-based probabilistic predictions generated by GuardX Gateway.</em>
            </div>

          </div>
        )}
      </div>

    </div>
  );
}
